### ISSUE TITLE
Homebrew install fail on Macbook

### ISSUE THREAD

**Issue by dukusb** [danieljprice/homebrew-all#1]
As per ...

~> brew list
aom		graphite2	libheif		mpfr		rubberband
cairo		harfbuzz	libmpc		nettle		sdl2
ffmpeg		hdf5		libogg		open-mpi	snappy
flac		icu4c		libomp		opencore-amr	speex
fontconfig	ilmbase		libpng		openexr		sqlite
freetype	imagemagick	libsamplerate	openjpeg	szip
frei0r		isl		libsndfile	openssl		tesseract
fribidi		jpeg		libsoxr		opus		theora
gcc		lame		libtasn1	p11-kit		unbound
gdbm		leptonica	libtiff		pcre		webp
gettext		libass		libtool		pixman		x264
giflib		libbluray	libunistring	python		x265
glib		libde265	libvorbis	python@2	xvid
gmp		libevent	libvpx		readline	xz
gnutls		libffi		little-cms2	rtmpdump
~> brew doctor
Your system is ready to brew.
~> brew tap danieljprice/all
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Tapping danieljprice/all
Cloning into '/usr/local/Homebrew/Library/Taps/danieljprice/homebrew-all'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Tapped 2 formulae (31 files, 50.8KB).
~> brew install splash
==> Installing splash from danieljprice/all
==> Installing dependencies for danieljprice/all/splash: isl, mpfr, gcc and giza
==> Installing danieljprice/all/splash dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.21.mojave.bottle.tar.
==> Downloading from https://akamai.bintray.com/f9/f9188b5d486b2a835cd865f219be1
######################################################################## 100.0%
==> Pouring isl-0.21.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.21: 72 files, 4.3MB
==> Installing danieljprice/all/splash dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.0.2.mojave.bottle.ta
==> Downloading from https://akamai.bintray.com/cf/cfce7ab866e98360c9364cd924da6
######################################################################## 100.0%
==> Pouring mpfr-4.0.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/4.0.2: 28 files, 4.7MB
==> Installing danieljprice/all/splash dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-9.1.0.mojave.bottle.tar
==> Downloading from https://akamai.bintray.com/1a/1af51e1a8c5394297c13b85548203
######################################################################## 100.0%
==> Pouring gcc-9.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/gcc/9.1.0: 1,461 files, 287MB
==> Installing danieljprice/all/splash dependency: giza
==> Downloading https://github.com/danieljprice/giza/releases/download/v1.1.0/gi
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/giza/1.1.0
==> make install
🍺  /usr/local/Cellar/giza/1.1.0: 31 files, 1.3MB, built in 39 seconds
==> Installing danieljprice/all/splash
==> Downloading http://users.monash.edu.au/~dprice/splash/releases/splash-2.9.0.
######################################################################## 100.0%
==> make SYSTEM=gfortran PREFIX=/usr/local/Cellar/splash/2.9.0/ GIZA_DIR=/usr/lo
Last 15 lines from /Users/luke/Library/Logs/Homebrew/splash/01.make:
      ___interpolations3dgeom_MOD_interpolate3dgeom_vec._omp_fn.0 in interpolate3D_geom.o
      ...
  "_GOMP_loop_nonmonotonic_guided_start", referenced from:
      ___projections3d_MOD_interp3d_proj_vec_synctron._omp_fn.0 in interpolate3D_projection.o
      ___projections3d_MOD_interpolate3d_proj_vec._omp_fn.0 in interpolate3D_projection.o
      ___projections3d_MOD_interpolate3d_projection._omp_fn.1 in interpolate3D_projection.o
      ___interpolations3d_MOD_interpolate3d_vec._omp_fn.0 in interpolate3D.o
      ___interpolations3d_MOD_interpolate3d._omp_fn.0 in interpolate3D.o
      ___interpolations3dgeom_MOD_interpolate3dgeom._omp_fn.0 in interpolate3D_geom.o
      ___interpolations3dgeom_MOD_interpolate3dgeom_vec._omp_fn.0 in interpolate3D_geom.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [mhutch] Error 1
make: *** [splash] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/danieljprice/homebrew-all/issues

**Comment by danieljprice** [comment]
I could not reproduce this on my laptop, must be some kind of conflict between gcc versions?
```% brew install splash
==> Installing splash from danieljprice/all
==> Installing dependencies for danieljprice/all/splash: isl and gcc
==> Installing danieljprice/all/splash dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.21.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f9/f9188b5d486b2a835cd865f219be1a9848ce3926e27089a1538ee989db65447d?__gda__=exp=1559022030~hmac=8fa40a9c0fd358c1411199b18af393f4e58f0922d626582a085694d295170bdb&response-content-disposition=attachment%3Bfilename%3D%22isl-0.21.
######################################################################## 100.0%
==> Pouring isl-0.21.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.21: 72 files, 4.3MB
==> Installing danieljprice/all/splash dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-9.1.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/1a/1af51e1a8c5394297c13b85548203a84279a2e24e6ab982fb299c526bdde3079?__gda__=exp=1559022033~hmac=bd0230d22fab2c3f6aaec99d2362470deaf68b43e918550b12834ddc4d822169&response-content-disposition=attachment%3Bfilename%3D%22gcc-9.1.0
######################################################################## 100.0%
==> Pouring gcc-9.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/gcc/9.1.0: 1,461 files, 287MB
==> Installing danieljprice/all/splash
==> Downloading http://users.monash.edu.au/~dprice/splash/releases/splash-2.9.0.tar.gz
Already downloaded: /Users/dprice/Library/Caches/Homebrew/downloads/8cfae4ac449597964a27ba19daa55d22430d3f8031c75854e9f09240c40324c2--splash-2.9.0.tar.gz
==> make SYSTEM=gfortran PREFIX=/usr/local/Cellar/splash/2.9.0/ GIZA_DIR=/usr/local CC=clang
==> make install PREFIX=/usr/local/Cellar/splash/2.9.0
🍺  /usr/local/Cellar/splash/2.9.0: 16 files, 18.9MB, built in 1 minute```

**Comment by dukusb** [comment]
Completely uninstalled homebrew and started again, but it works. Cheers.
